Repository php-llm/llm-chain-bundle, pull requests merged in 2024-09, with the labels that each got.

#27 fix: chroma db namespace
  composer.json
  src/DependencyInjection/LlmChainExtension.php
  src/Resources/config/services.php
Labels: bug

#24 Add support for new MongoDB store
  README.md
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/LlmChainExtension.php
  src/Resources/config/services.php
Labels: enhancement

#30 Set default values
  src/DependencyInjection/Configuration.php
Labels: bug

#33 Require `php-llm/llm-chain` 0.4
  composer.json
Labels: dependency
