Repository php-llm/llm-chain-bundle, pull requests merged in 2025-03, with the labels that each got.

#71 ci: streamline with lib
  .github/workflows/pipeline.yml
  Makefile
Labels: CI/CD

#68 feat: support include tools feature to system prompt
  README.md
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/LlmChainExtension.php
Labels: enhancement, feature

#73 chore: lib update
  composer.json
  src/Resources/config/services.php
  src/Resources/views/data_collector.html.twig
Labels: chore

#75 feat: add inline tool definition and chain in chain 🤯
  README.md
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/LlmChainExtension.php
  src/Resources/config/services.php
Labels: feature
